version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - connection

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    depends_on:
      - zookeeper
    ports:  
      - "9092:9092"

    expose:
      - "9093"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://broker:9093,OUTSIDE://localhost:9092,DOCKER://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    networks:
      - connection

  nifka:
    image: apache/nifi:latest
    container_name: nifka
    depends_on:
      - kafka
      - broker-service
      - producer-service
    ports:
      - "8080:8080"
    environment:
      NIFI_WEB_HTTP_PORT: "8080"

    networks:
     - connection

  broker-service:
    image: broker:latest
    container_name: broker-s
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    networks:
      - connection

  producer-service:
    image: producer:latest
    container_name: producer
    depends_on:
      - kafka
      - broker-service
    ports:
      - "8082:8082"
    networks:
      - connection

networks:
    connection:
      driver: bridge

